---

- name: import pr jobs
  shell: "{{ jenkins_cli }} create-job pr.{{ item }} < {{ jenkins_install }}/jobs/pr.{{ item }}.xml"
  with_items: "{{ repos }}"

- name: import snapshot jobs
  shell: "{{ jenkins_cli }} create-job snapshot.{{ item }} < {{ jenkins_install }}/jobs/snapshot.{{ item }}.xml"
  with_items: "{{ repos }}"
